### ISSUE TITLE
[Feat] Group 기능 추가

### ISSUE THREAD

**Issue by ryulkim** [TIG-Inha/TimeIsGold_Backend#26]
:exclamation:**이슈내용**
---
- Group 기능을 통해 그룹에 속한 사람들의 시간표를 합쳐 가능한 시간을 추출하도록 한다.

:star:**상세 내용**
---
1. Group `생성`을 하면 `OTP`가 발급된다.
2. Group `참여`는 `OTP`를 입력하면 참여가 된다.
3. 생성자와 참여자 모두에게 `참여자 수`가 뜬다.
4. 생성자가 `그룹 생성 버튼`을 눌렀을 때, `가능한 시간`이 추출된다.

:white_check_mark:**체크리스트**
---
- [x] 그룹 시작 api #27 
- [x] 그룹 OTP api #50
- [x] 그룹 참여 api #34
- [x] 그룹 취소 api #39 
- [x] 그룹 생성 api #40
- [x] 그룹 시간표 보기 api #45 

+밑 comment에 결과 있음

**Comment by ryulkim** [comment]
## 최종 완성본
```
user1, user2가 한 그룹
user1의 tableId: 5
user2의 tableId: 9
```
- Schedule
![image](https://user-images.githubusercontent.com/58160874/227757706-37911344-1ff4-4ec2-a335-70b9be15d9e0.png)

- 그룹 생성자
![image](https://user-images.githubusercontent.com/58160874/227757808-68a4d49f-e581-4494-b520-a259fd03405e.png)
sse를 통해 생성하고 참여할 때마다 sse에서 실시간 참여 수를 전달하는 걸 볼 수 있다.

- 그룹 참여자
![image](https://user-images.githubusercontent.com/58160874/227757768-e1fd13ca-bd2d-4f96-a9c8-113b46233a9b.png)

- 그룹 시간표 추출
![image](https://user-images.githubusercontent.com/58160874/227757846-1b026280-ddf3-46a2-a2c4-cac94196faa9.png)
응답 값: 그룹 id
![image](https://user-images.githubusercontent.com/58160874/227757926-bc229a3d-eae8-415d-9bc6-4c40af693124.png)
응답 값: 가능한 시간

- Table
![image](https://user-images.githubusercontent.com/58160874/227758023-51fe8dd8-c28e-4da7-aad4-0ab26e8d241b.png)
![image](https://user-images.githubusercontent.com/58160874/227758164-412c0445-312b-4778-862e-4a39368bd475.png)
![image](https://user-images.githubusercontent.com/58160874/227758027-de476317-8feb-4f8c-ae50-57e4dec64bf4.png)
![image](https://user-images.githubusercontent.com/58160874/227757706-37911344-1ff4-4ec2-a335-70b9be15d9e0.png)
